"""BSage demo vault seeding — pre-populate the shared demo tenant's
vault with realistic notes so the visitor's vault, search, and graph
panels render real content instead of empty directories.

Runs at startup when ``BSVIBE_DEMO_MODE=true``. Idempotent: a sentinel
file under the vault root is checked first; subsequent boots skip the
seed entirely.

Notes carry ``tenant_id: <DEMO_SHARED_TENANT_ID>`` in their YAML
frontmatter so the existing tenant filter in ``bsage.gateway.routes``
admits them for demo visitors.
"""

from __future__ import annotations

from pathlib import Path

import structlog

from bsage.demo.auth import DEMO_SHARED_TENANT_ID

logger = structlog.get_logger(__name__)

_SENTINEL = ".demo_seeded"


def _note(
    tenant_id: str, title: str, body: str, *, tags: list[str], note_type: str = "idea"
) -> str:
    tags_yaml = "[" + ", ".join(tags) + "]"
    return (
        "---\n"
        f"tenant_id: {tenant_id}\n"
        f"type: {note_type}\n"
        "status: growing\n"
        "source: demo-seed\n"
        f"tags: {tags_yaml}\n"
        "---\n\n"
        f"# {title}\n\n"
        f"{body}\n"
    )


_NOTES: list[tuple[str, str, str, list[str], str]] = [
    (
        "garden/bsvibe-overview.md",
        "BSVibe at a glance",
        (
            "BSVibe is a four-product stack for running an AI-native company:\n\n"
            "- **BSNexus** — the founder's chat-of-staff that turns direction into work.\n"
            "- **BSGateway** — cost-aware LLM routing across providers.\n"
            "- **BSupervisor** — agent auditing, blocking, and forensic timelines.\n"
            "- **BSage** — the personal 2nd-brain. You're reading a note from it.\n\n"
            "See [[Onboarding playbook]] for the customer-facing sequence."
        ),
        ["bsvibe", "overview"],
        "evergreen",
    ),
    (
        "garden/onboarding-playbook.md",
        "Onboarding playbook",
        (
            "Day 1 — welcome email + booking link to a 15-min office hour.\n"
            "Day 2 — interactive demo invite (this very page).\n"
            "Day 4 — first-week digest summarising activity.\n"
            "Day 7 — case-study walkthrough with a customer in the same vertical.\n\n"
            "Reflects the live spec of [[BSVibe at a glance]]."
        ),
        ["customer", "playbook"],
        "evergreen",
    ),
    (
        "garden/landing-page-research.md",
        "Landing page research notes",
        (
            "Heatmaps from the last cohort show 64% of visitors bouncing in\n"
            "the hero section. Dominant friction:\n\n"
            "1. Headline asks the visitor to identify their persona before\n"
            "   they understand the product.\n"
            '2. CTA is below the fold on 13" laptops.\n'
            "3. No demo without sign-up.\n\n"
            "See [[Hero copy v2 draft]] for the rewrite proposal."
        ),
        ["research", "landing"],
        "idea",
    ),
    (
        "garden/hero-copy-v2-draft.md",
        "Hero copy v2 draft",
        (
            "**Hire your AI company.** Direct it from a single chat. Watch it\n"
            "ship — under your audit, with your knowledge, on your budget.\n\n"
            'Primary CTA: "Try the demo →". Secondary: "Read the architecture".\n\n'
            "Approved variant referenced in [[Landing page research notes]]."
        ),
        ["copy", "landing"],
        "idea",
    ),
    (
        "garden/customer-research.md",
        "Customer research interviews",
        (
            "Five 30-minute interviews with prospective design partners:\n\n"
            "- Two YC founders ship-blocked on safety review for agentic features.\n"
            "- Two infra leads at growth-stage SaaS evaluating LLM-cost guardrails.\n"
            "- One solo developer wanting a personal 2nd brain that won't lock them in.\n\n"
            "Cross-references: [[Onboarding playbook]], [[BSVibe at a glance]]."
        ),
        ["research", "customers"],
        "idea",
    ),
    (
        "garden/weekly-digest.md",
        "Weekly digest — week of demo launch",
        (
            "Highlights:\n\n"
            "- Demo went live across all 4 products with shared auth.bsvibe.dev path.\n"
            "- Routing test endpoint now correctly differentiates URGENT vs ordinary.\n"
            "- BSupervisor seeded 14 audit events to populate the timeline.\n"
            "- Three blocked events surfaced: API key exposure, prompt injection, cost ceiling.\n\n"
            "Generated by the weekly-digest skill from notes under garden/."
        ),
        ["digest", "weekly"],
        "insight",
    ),
    (
        "garden/safety-rules-cheatsheet.md",
        "BSupervisor safety rules — cheatsheet",
        (
            "Quick reference for the 8 default rules shipped in the demo:\n\n"
            "1. API Key Exposure — block outputs with sk-ant-/sk-or-/sk-proj- prefixes.\n"
            "2. Prompt Injection — block ignore-previous-instructions phrasing.\n"
            "3. Per-Request Cost Ceiling — block single calls > $1.00.\n"
            "4. Daily Cost Ceiling — alert at 80%, block at 100% of daily budget.\n"
            "5. PII Leakage — block emails / SSNs / phone numbers in outbound payloads.\n"
            "6. External Domain Allow-list — only allow tool calls to listed hosts.\n"
            "7. Destructive SQL — block DROP / TRUNCATE / DELETE without WHERE.\n"
            "8. Credential Filesystem Access — block reads of /etc/, ~/.ssh/, etc.\n\n"
            "All eight ship pre-installed. See [[Customer research interviews]] for the\n"
            "feedback that drove the additions."
        ),
        ["safety", "supervisor"],
        "evergreen",
    ),
    (
        "actions/2026-05-06_run.md",
        "2026-05-06 — Demo seed run",
        (
            "Seeded the BSage demo vault with 7 garden notes and 1 action log entry.\n"
            "Source: bsage.demo.seed (idempotent, sentinel-gated)."
        ),
        ["log", "demo"],
        "log",
    ),
]


def seed_demo_vault(vault_root: Path) -> int:
    """Write seed notes under ``vault_root``. Returns count written.

    A sentinel file under ``vault_root`` short-circuits subsequent calls
    so we never duplicate or overwrite visitor edits across restarts.
    """
    sentinel = vault_root / _SENTINEL
    if sentinel.exists():
        return 0

    vault_root.mkdir(parents=True, exist_ok=True)
    written = 0
    tenant_id = str(DEMO_SHARED_TENANT_ID)
    for rel, title, body, tags, note_type in _NOTES:
        target = vault_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_note(tenant_id, title, body, tags=tags, note_type=note_type))
        written += 1

    sentinel.write_text("seeded\n")
    logger.info("demo_vault_seeded", vault_root=str(vault_root), notes=written)
    return written
